-- Testdaten werden NICHT mehr per COPY in dieser Init-Datei geladen.
--
-- Grund: Die Quell-CSVs sind fuer ein direktes COPY zu unsauber:
--   * eingebettete Header-Zeilen mitten in den Daten (k_plz, fm_gebaeude)
--   * unquotierte Trennzeichen in Textfeldern (fm_gebaeude, fm_inst)
--   * doppelt-kodierte Umlaute ("GebÃ¤ude") und vereinzelt NUL-Bytes (fm_inst)
-- COPY laeuft im Postgres-Init mit ON_ERROR_STOP und brach beim ersten Fehler ab,
-- wodurch ALLE folgenden Tabellen leer blieben.
--
-- Stattdessen laden tolerante Python-Loader die Daten NACH dem Container-Start.
-- Sie werden von scripts/install.ps1 ausgefuehrt (Host-Python ODER Docker-Fallback):
--   fm_gebaeude  -> scripts/load_fm_gebaeude.py
--   k_plz        -> scripts/load_k_plz.py
--   fm_inst      -> scripts/load_fm_inst.py
--   fm_rna       -> scripts/load_json.py
--   hso_personal -> scripts/load_json.py
--
-- Nicht geladen:
--   * hso_students.csv ist strukturell defekt (Datenzeilen haben mehr Spalten als
--     der eigene Header). Studierendendaten daher ueber den Airbyte File-Connector
--     beziehen (siehe docs/airbyte-setup.md, Abschnitt 7).
--   * fm_stamm hat keine Quelldatei -> Tabelle bleibt leer.
--
-- Die Tabellen-Schemata werden weiterhin in 00_tables.sql angelegt.
